/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module logic_game (
  input A,
  input B,
  input C,
  input D,
  output Y
);
  assign Y = (~ D & (C | (B & A)));
endmodule
